name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 运行器
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Enable macOS build
      run: flutter config --enable-macos-desktop
    
    - name: Build macOS
      run: flutter build macos --release
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@main
      with:
        name: macos-app
        path: build/macos/Build/Products/Release/*.app
